AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-2

  Sample SAM Template for aws-lambda-2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  Runtime:
    Type: String
    Default: java11
    Description: Language runtime name to use for Lambda function execution
  MemorySize:
    Type: Number
    Default: 512
    Description: Memory capacity for Lambda function execution

Resources:
  S3CreateBucketFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: S3CreateBucketFunction
      Handler: com.epam.aws.lambda.App::handleRequest
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        BucketList:
          Type: Api
          Properties:
            Path: /buckets
            Method: post
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
            Resource: "*"

